name: Paster
options:
  bundleIdPrefix: com.macpaste
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  macPaste:
    type: application
    platform: macOS
    sources:
      - path: macPaste
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_NAME: Paster
        PRODUCT_BUNDLE_IDENTIFIER: com.macpaste.app
        INFOPLIST_FILE: macPaste/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: NO
        NSPrincipalClass: NSApplication
    entitlements:
      path: macPaste/Resources/macPaste.entitlements
